### ISSUE TITLE
[iOS] 구글 로그인 클릭시 충돌 증상

### ISSUE THREAD

**Issue by HyunheeKo** [coolishbee/universal-sdk-unity#10]
## What did you do?

iOS 에 애플&구글 로그인을 구현 하고 있습니다.

아이폰을 맥에 연결하여 XCode 에서 실행하면 애플 및 구글 로그인이 잘됩니다.

그런데 스토어에 등록해서 다운받아서 진행하니 애플은 여전히 잘되는데 

구글을 버튼을 누르는 순간 앱이 죽어버립니다.

되게 난감한 상황인데 도움을 주실수 있을까요?

이문제로 48시간째 작업중입니다.

![image](https://user-images.githubusercontent.com/6635625/198358038-0f00373a-7b2a-4a74-8085-e96b1dc9b303.png)

## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

> Please describe what happened actually.

## Your environment?

> Some information of the environment in which the issue happened. Universal SDK version, Unity version, Android version, iOS version, etc.

## Screenshots or Log

> It would be appreciated if you can provide a screenshot or log that i can infer the issue.

**Comment by coolishbee** [comment]
Xcode > Devices ans Simulators 를 사용해서 크래시 로그를 확인해보시겠어요?

**Comment by HyunheeKo** [comment]
답변 감사합니다.
이 문제를 해결하였습니다.
xcode 13.4를 사용하고 있었는데... xcode를 14로 업로드 하니 해당 문제가 없어졌습니다.
애플의 문제라고 잠정적으로 판단하고 있습니다.
그럼 수고하세요~
