### ISSUE TITLE
Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.

### ISSUE THREAD

**Issue by jsa9292** [coolishbee/universal-sdk-unity#11]
## What did you do?

> tried apple login from android build
After apple id and pw
after "Do you want to continue using ... login with your Apple ID "email@email.com"?
"Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared." appears without error or log in.

## What did you expect?

> logging in

## What happened actually?

> https://github.com/firebase/firebase-js-sdk/issues/4256

## Your environment?

> iOS SDK Version : 1.1.2
Android SDK Version : 1.1.5
Unity SDK Version : 1.1.4
Unity 2021.3.11f1

## Screenshots or Log

> Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.

**Comment by jsa9292** [comment]
한국인입니다 편한 언어로 답변 부탁드립니다.

**Comment by coolishbee** [comment]
안드로이드 애플로그인 이슈인가요? 혹시 이전 [이슈트레킹](https://github.com/coolishbee/universal-sdk-unity/issues/5)으로 해결이 안된다면 상세하게 설명 부탁드릴게요

**Comment by jsa9292** [comment]
안드로이드 빌드에서 애플로그인 때에 https://github.com/firebase/firebase-js-sdk/issues/4256 에서 얘기하는 메시지가 위에 주소바 없이 뜹니다. 그다음에 로그인이 진행이 안돼요. 
공유해주신 이슈랑은 다른 이슈인걸로 판단됩니다.
저쪽 쓰레드는 읽어봤는데 js-sdk 기준이라 그런지 참고할만한게 딱히 없더라구요. 도와주세요 ㅠㅜ

**Comment by coolishbee** [comment]
애초에 웹뷰라서 주소바를 띄우지는 않거든요 [이 부분](https://github.com/coolishbee/universal-sdk-unity/blob/main/docs/en/README.md#apply-social-id-to-project)에 apple_client_id, redirect_url 셋팅하셨는지 한번 확인해보세요
안드로이드 애플로그인은 redirect 서버없이는 사용이 불가능해요;;

**Comment by jsa9292** [comment]
둘다 입력했고 안드로이드 구글 로그인은 제대로 작동하는데 혹시 애플 로그인용 REDICRECT URL이 따로 있나요?

**Comment by coolishbee** [comment]
네네 안드로이드에서 애플로그인할때는 애플정책으로 필수사항이에요 그 내용이 정리된게 위에 언급한 [이슈트레킹](https://github.com/coolishbee/universal-sdk-unity/issues/5)이에요
제가 지금 코로나 확진으로 인해 몸상태가 매우 좋지 않아서 답장이 느릴 수 있어요;;

**Comment by jsa9292** [comment]
아프신데도 답변 감사합니다! 제가 서버쪽은 잘 몰라서 그런데 파이어베이스쪽에서 그 redirect를 할수 있는 방법이 있을까요? 답변 천천히 주셔도 됩니다! 답변 남기고 자체적으로 계속 찾아보는 중입니다. 해결하면 여기 다시 댓글 남기겠습니다. :)

**Comment by coolishbee** [comment]
firebase 로 하려면 firebase 에 있는 애플로그인 provider 로 구현하셔야 할 거에요
결론만 말씀드리면 firebase redirect 로는 안되세요 callback 처리가 다르기도 하고 token 2차검증까지 포함된거라서 제가 하는 방식과는 다릅니다. 도움이 되지 못해 죄송합니다.

**Comment by adityaarya99** [comment]
To do it with firebase, you'll need to implement it as an app login provider in firebase.
In conclusion, it is not possible with firebase redirect. The callback handling is different and it includes token secondary verification, so it is different from the way I do it. Sorry for not being helpful.

**Comment by adityaarya99** [comment]
To do it with firebase, you'll need to implement it as an app login provider in firebase.
In conclusion, it is not possible with firebase redirect. The callback handling is different and it includes token secondary verification, so it is different from the way I do it. Sorry for not being helpful.

**Comment by adityaarya99** [comment]
Are you Alive @jsa9292?

**Comment by adityaarya99** [comment]
Korean:  우리는 귀하의 모든 대화를 유용하지 않게 번역했습니다. Google을 통해 캘린더 초대를 생성하는 동안 Flutter 웹에서 동일한 문제에 직면하고 있습니다. 도움이 필요하시면 알려주세요.

English: We translated all your conversation nothing useful. I'm facing the same issue in flutter web while generating a calender invite through google. Let me know if you can help.
