### ISSUE TITLE
App crashes after clicking on Login with Facebook live app (app is live on google store)

### ISSUE THREAD

**Issue by 2ez4tt** [coolishbee/universal-sdk-unity#13]
## What did you do?

> I pressed login with facebook and app crashes 

## What did you expect?

> it should login with facebook

## What happened actually?

> After completing app check and going live on google play store when I login using facebook app crashes. it was working fine for admins of app before in both development and live mode but giving error for other users. After completing app checkup (setting advance access for both email and login) for facebook app now it crashes for other users when logged in.

## Your environment?

> Unity version 2021.3.16, Android version 33, 

## Screenshots or Log

> It would be appreciated if you can provide a screenshot or log that i can infer the issue.

**Comment by 2ez4tt** [comment]
![Capture](https://user-images.githubusercontent.com/17083237/211322340-39298b7b-e534-4c97-a5e8-9c39755fcdb7.PNG)

could this be the problem because it is not working on devices above android 11? tried few with android 11 its working

**Comment by coolishbee** [comment]
So far, no crash logs have been reported from Facebook login. It seems that the low version of the facebook sdk is not the cause. Try tracing the crash log using adb logcat? I need an error message to figure out the cause.

**Comment by 2ez4tt** [comment]
![image](https://user-images.githubusercontent.com/17083237/211360274-60b36cfe-d3f3-41cb-89e2-d0953d5b5a40.png)
does this help?

**Comment by 2ez4tt** [comment]
issue was resolved by adding this in mainTemplate.gradle

I also want to ask
1) Can I remove this somehow if I am not using apple login? because it
gives error in release report in playstore .

Your app performs authentication via WebViews, which leads to security and
usability issues. Please see this Google Help Center article
<https://support.google.com/faqs/answer/12284343> for details.

   - io.github.jameschun7.auth.AppleLoginActivity.appleAuth


TIA

**Comment by coolishbee** [comment]
Support issue for Targeting S+ (version 31 and above). Thanks for the crash log.
Support for Targeting S+ (version 31 and above) is currently being prepared. I'll make it available as soon as possible.

In the case of Apple login, there is currently no way other than webview to support Android. It is currently difficult to selectively take this. I'll think of a good idea.
