### ISSUE TITLE
Android build crashes right after start

### ISSUE THREAD

**Issue by Leonard0SSilva** [coolishbee/universal-sdk-unity#14]
## What did you do?
1. Set the project to Android IL2CPP
2. Enable arm64
3. Build
4. Install on Android
5. App Crashes on load

## What did you expect?
app launches normally

## What happened actually?
the app starts launching and crashes with the exception

## Your environment?
[Universal SDK](https://github.com/coolishbee/universal-sdk-unity)
Unity 2021.3.16f1 | SILICON | LTS
Target Android API level 30
Device: 
Android Studio
<img width="194" alt="Screenshot 2023-01-24 at 10 26 34" src="https://user-images.githubusercontent.com/19909277/214306669-023fb454-9230-4afd-bf09-6e830951987d.png">

**Comment by coolishbee** [comment]
Sorry, I'm not considering Android emulator support yet. So I haven't even tested this part.
