### ISSUE TITLE
  Reason: tried: '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache)

### ISSUE THREAD

**Issue by zkdhtm246** [coolishbee/universal-sdk-unity#16]
안녕하세요 먼저 좋은 SDK를 제공해주신점 감사드립니다
저는 안드로이드에서 본 sdk를 통해 구글 로그인을 구현하였습니다

현재 유니티를 사용하고있으며 버전은 2021.3.0f1 입니다
현재 주요 패키지는 아래와 같습니다

firebase cloud Firestore(10.5.0)
firebase Authentication(10.5.0)
Google Mobile Ads for Unity(7.3.1)
External Dependency Manager(1.2.175)

원하는 것은 iOS에서 구글 로그인을 구현하는 것 입니다
하지만, iOS에서 많은 문제가 발생했고 어떻게든 빌드에 성공했습니다(본 sdk와는 무관한 이슈였음)

현재 iOS 빌드 후, 앱을 실행하는 경우 어디 장면이든 검은 화면에서 앱이 강제 종료되며 아래와 같은 에러가 나타납니다.

  Reason: tried: '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/UniversalSDKSwift.framework/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (code signature invalid in <34FFD5EA-7C36-33F2-A3BF-A53AA46694C0> '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/UniversalSDKSwift.framework/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x0037E130, codeBlobSize=0x0000B810), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/preboot/Cryptexes/OS@rpath/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/UniversalSDKSwift.framework/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (code signature invalid in <34FFD5EA-7C36-33F2-A3BF-A53AA46694C0> '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/UniversalSDKSwift.framework/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x0037E130, codeBlobSize=0x0000B810), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/private/var/containers/Bundle/Application/161E7F99-D97B-47CB-A8E1-CEED60DFDD42/ProductName.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/System/Library/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache)

저는 이 에러가 FacebookSDK라는 사실을 깨달았으나 이것은 제외하고 빌드하는 법은 알지 못하였습니다.
저는 안드로이드와 아이폰에서 오로지 구글 로그인만 사용할 생각입니다(필요에 따라 애플 로그인 사용 할 수 있음)

제가 조언해줄 수 있는 해결 방법이 있을까요?

ps. UniversalSDK->Edit Setting에서 페이스북과 애플 로그인 체크박스를 풀고(false) Facebook AppID와 Facebook ClientToken은 공백으로 두고 iOS빌드를 해보았고 기본 예시(샘플) 내용을 그대로 둔채 빌드 또한 해보았습니다.

**Comment by wjdwltn200** [comment]
*아이디는 다르지만 동일인물입니다
이 문제를 해결했습니다 원인은 정확하게 모르겠으나 저는 온갖 방법을 써보고나서, 자포자기 심정으로 샘플로 올려주신 내용물을 그대로 적용해보았고 정상 동작하였습니다 정확하게는 "Assets"만 붙여보았고 붙일때 중복되는 것을 모두 지운 상태에서 진행했습니다.

순서(Unity 환경에서 수행)
1. 기존에 설치되어있던 모든 SDK 삭제(전부다)
2. 샘플 SDK(https://github.com/coolishbee/universal-sdk-unity-demo)를 다운 내용물에서 "Assets"폴더를 프로젝트 "Assets"에 그대로 붙여넣기
3. 사전에 충돌되는 폴더는 모두 제거(끝에~를 붙여 폴더 숨김처리)
4. Unity에서 iOS빌드 -> xCode에서 iOS빌드 => 성공

다시 한번 유용한 통합 로그인 관리 SDK를 제공해주셔서 감사합니다.

**Comment by coolishbee** [comment]
안녕하세요

위 에러로그만으로는 바로 파악이 안되네요. 혹시 에러 나던 프로젝트 공개가 가능하시다면 github 저장소 링크를 알려주신다면 도움을 드릴 수 있을 것 같습니다.
그리고 [문서](https://chc3484.gitbook.io/sdk/v/ko/unity-sdk/integrations#plugins-settting)내용에 있는 Plugins 폴더위치도 체크 부탁드립니다.

**Comment by wjdwltn200** [comment]
> 안녕하세요
> 
> 위 에러로그만으로는 바로 파악이 안되네요. 혹시 에러 나던 프로젝트 공개가 가능하시다면 github 저장소 링크를 알려주신다면 도움을 드릴 수 있을 것 같습니다. 그리고 [문서](https://chc3484.gitbook.io/sdk/v/ko/unity-sdk/integrations#plugins-settting)내용에 있는 Plugins 폴더위치도 체크 부탁드립니다.

안녕하세요 질문자 입니다 프로젝트는 개인 소유가 아니라 공유가 어려울 것 같습니다 위에 기재한 것 처럼 문제는 해결하였습니다.

해결된 시점이라 정확한 원인 추적은 어려워 명확하게는 모르겠으나 폴더의 위치가 문제라고 생각됩니다. 이것은 또다른 추측입니다만 제가 본 SDK를 사용했을 당시 여러 SDK를 사용하고있던 터라 충돌이 났었을 것으로도 생각됩니다.

그래서 위에 쓴 것 처럼 기존 SDK를 모두 제거한 상태에서 시작하였기 때문에 해결되었지 않았나 생각하고 있습니다.

오히려 명확하게 문제 해결 방법과, 원인을 설명하지 못한점 양해 부탁드리며 다시 한번 유용한 SDK를 제공해주신점에 대해 감사드립니다. 여러모로 많은 공부가 되었습니다.

**Comment by coolishbee** [comment]
문제가 해결되었다니 다행입니다:)
