### ISSUE TITLE
구글 플레이 콘솔 'io.github.coolishbee.auth.AppleLoginActivity.onCreate' 에러

### ISSUE THREAD

**Issue by wjdwltn200** [coolishbee/universal-sdk-unity#17]
안녕하세요 구글 플레이 콘솔 업로드 과정에서 에러가 발생하여 문의 드립니다.

![Test](https://user-images.githubusercontent.com/25091768/228214284-3c00fe62-1c53-4884-a10c-0df393665c9b.png)

출처가 명확해서 이쪽에 이슈 글을 작성하였습니다.
혹시 제가, 무언가 놓친게 있을까요?

**Comment by coolishbee** [comment]
안녕하세요
이 메시지는 일종의 warring 유형이고 관련해서 업데이트했으나 공식업데이트가 아니기때문에 UniversalSDKDependencies.xml 을 통해서
버전 업데이트해주시길 바랍니다.
> 3.0.2 -> 3.0.3 로 변경하여 새로 빌드후 출시해보세요~!

`<androidPackage spec="io.github.coolishbee:universalsdk:3.0.3"/>`

**Comment by wjdwltn200** [comment]
제시해주신 방법을 사용하니 에러가 사라졌습니다 감사합니다!
