### ISSUE TITLE
ios app crashing issue

### ISSUE THREAD

**Issue by bossturk** [coolishbee/universal-sdk-unity#18]
I am downloading the demo project, configuring the settings, and when I build it for iOS, there is no problem. However, when I open the application on my phone, I receive the following error:

2023-05-21 02:50:03.176692+0300 UnityDemo[18439:6348072] [general] Error loading /var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/UnityFramework.framework/UnityFramework (136):  dlopen(/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: <107B5D1E-567D-3247-9593-F82DF543660D> /private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/UniversalSDKSwift.framework/UniversalSDKSwift
  Reason: tried: '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/UniversalSDKSwift.framework/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (code signature invalid in <34FFD5EA-7C36-33F2-A3BF-A53AA46694C0> '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/UniversalSDKSwift.framework/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x0037E130, codeBlobSize=0x0000B810), '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/System/Library/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file, not in dyld cache)
2023-05-21 02:50:05.390338+0300 UnityDemo[18439:6348072] [general] Error loading /var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/UnityFramework.framework/UnityFramework (136):  dlopen(/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: <107B5D1E-567D-3247-9593-F82DF543660D> /private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/UniversalSDKSwift.framework/UniversalSDKSwift
  Reason: tried: '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/UniversalSDKSwift.framework/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (code signature invalid in <34FFD5EA-7C36-33F2-A3BF-A53AA46694C0> '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/UniversalSDKSwift.framework/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x0037E130, codeBlobSize=0x0000B810), '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/private/var/containers/Bundle/Application/0BB3343D-78C2-4205-B78C-734A9182A1B2/UnityDemo.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file), '/System/Library/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (no such file, not in dyld cache)

**Comment by coolishbee** [comment]
Sorry, the sdk in the current demo is not the latest version. There was a
problem with Facebook's latest sdk, so it was updated. Please use the
latest version through the Asset Store.

2023년 5월 21일 (일) 오후 11:03, bossturk ***@***.***>님이 작성:
