### ISSUE TITLE
Login Failed when Login with Google

### ISSUE THREAD

**Issue by cperisson1** [coolishbee/universal-sdk-unity#2]
Hi.  

Unity build and deploy on device works without any problem. I can sign with Google, but then the app show the attached screen, this message: 

"Login Failed.(10)"

The GoogleClientID and ReverseId are configurated. Tested with several Google users

Any help?

Anyway, great product!!!

Thanks in advance

![Screenshot_20220802-125332_Login with Google Universal](https://user-images.githubusercontent.com/78812796/182358194-66068104-8064-48ba-a240-2545d180781b.jpg)

**Comment by coolishbee** [comment]
If error code 10 is the result when trying to Google Login, you need to check whether the certificate fingerprint is registered in the firebase console.

Register the SHA-1 certificate thumbprint of each app signing key certificate and upload key certificate in Google Play Console App Settings > App Integrity tab in Firebase Console > Project settings > General tab.

![setting](https://user-images.githubusercontent.com/20632507/147073695-02faf079-66b3-4af8-98e4-5c907a68190f.png)

To enable Google login for both the version released on the Google Play Console and the version directly distributed by the developer with the same certificate, you must register both the upload key certificate and the app signing certificate fingerprint.
