### ISSUE TITLE
LDPlayer에서 Apple 로그인 시도시 크롬없이 로그인이 안됨

### ISSUE THREAD

**Issue by cookapps-thkim2** [coolishbee/universal-sdk-unity#21]
## What did you do?

> Please describe what you did before you encounter the issue.

LDPlayer9에서 Apple Login 시도시 크롬을 설치해야 합니다.

## What did you expect?
> Please describe what you did expect to happen.

크롬없이 Apple 로그인이 되면 좋을 것 같습니다.

## What happened actually?
> Please describe what happened actually.

크롬이 없으면 크롬을 설치하라는 경고가 뜹니다. (의도한 팝업인 듯 합니다)

## Your environment?
> Some information of the environment in which the issue happened. Universal SDK version, Unity version, Android version, iOS version, etc.

UniversalSDK 1.2.4 사용했습니다.

## Screenshots or Log

> It would be appreciated if you can provide a screenshot or log that i can infer the issue.

**Comment by coolishbee** [comment]
LDPlayer v9 버전에서 커스텀탭스를 실행할수 없을때는 기본브라우저로 애플로그인을 실행하도록 업데이트하였습니다.
배포까지는 약 2-3일 소요될 것 같습니다.

**Comment by coolishbee** [comment]
아래와 같이 업데이트 할 수 있습니다.

UniversalSDKDependencies.xml 사용시 :
`<androidPackage spec="io.github.coolishbee:universalsdk:3.0.6"/>`
mainTemplate.gradle 사용시 :
` implementation 'io.github.coolishbee:universalsdk:3.0.6'`

에셋스토어 출시는 1-2일 소요됩니다.

**Comment by cookapps-thkim2** [comment]
잘 되네요. LDPlayer9에서 크롬이 아닌 기본 브라우저로 로그인창 뜨는 것 확인했습니다. 감사합니다
