### ISSUE TITLE
Where do I put my google clientID and reverseClientID?

### ISSUE THREAD

**Issue by nextdaysoft** [coolishbee/universal-sdk-unity#22]
So, My question is where do I add the clientID and reverseClientID to get the response because for now it is showing "code":7003,
"message":"googleClientID is empty" and I'm new in unity to use it so where do I implement it in ios. I implemented both in info pList but it doesn't give any response and facebook is properly working and I add the appID in info.plist it's working but google doesn't. Please help!!!

**Comment by coolishbee** [comment]
Please refer to the [console guide](https://chc3484.gitbook.io/sdk/console-guide/google-login/ios) and enter it in the [UniversalSDKSetting.asset](https://chc3484.gitbook.io/sdk/unity-sdk/get-started/ios-setup) file.
