### ISSUE TITLE
Google Login on Android not working while exporting .aab with split application binary

### ISSUE THREAD

**Issue by eriol24** [coolishbee/universal-sdk-unity#23]
Hi, I am facing problems on **Google Login** with **Android** only.

I think my setup is correct because .apk is working as expected.

But when it comes to .aab with split application binary on, Google Login returns 7002 Login Failed(10) to me.

Is that something not being handled while exporting .aab with split application binary on ?

Thank you.

**Comment by coolishbee** [comment]
Hi,

The difference between apk and aab is irrelevant.

The certificate fingerprint used when building must be registered in [firebase or google api console](https://github.com/coolishbee/universal-sdk-unity-demo#google-login-certificate-thumbprint-settings).

For more information, please refer to the issue #2.

Thanks!

**Comment by eriol24** [comment]
Thanks for the reply.

For now, I can assume these setups are configured correctly because .apk works, right?
- Unity project setup
- All gradle/template setup
- Google OAuth2 web client id

So the main difference is **Firebase**.

I find that I have missed your guide about adding both app signing & upload certificate key, sorry about that.

I add it back, download and import the latest version of services json file, I still get the same error code and message.

By the way, I have imported the firebase unity plugin before using this plugin, don't know if impact or not.

Thanks again.

**Comment by coolishbee** [comment]
Registering the certificate fingerprint through the Firebase console is just to use the Google API console easily. In other words, you can register the certificate fingerprint in Google API console instead of Firebase.

Therefore, there is no conflict between universal sdk and firebase sdk.

Thanks!

**Comment by eriol24** [comment]
Do you mean that I can remove all SHA-1 from firebase console,

then create OAuth Client using my package name and Upload / App Signing SHA-1 ? (Which one)

And then replace the value in this line ?
resValue("string", "google_web_client_id", "value")

So it still works if I use Android Application type of OAuth2, instead of Web application ?

Sorry for not familiaring with Google/Android stuffs.

**Comment by coolishbee** [comment]
> Do you mean that I can remove all SHA-1 from firebase console, then create OAuth Client using my package name and Upload / App Signing SHA-1 ? (Which one)

In the simplest terms, the upload key certificate is used before the app is released to the store, and the app signing certificate is used after the app is released to the store. Therefore, multiple registrations are possible.

> And then replace the value in this line ?
> resValue("string", "google_web_client_id", "value")
> So it still works if I use Android Application type of OAuth2, instead of Web application ?

Yes, Android must be registered as a Web application type to work. I don't know why. But every time I build, even if the certificate changes, the value doesn't change.

Thanks!

**Comment by eriol24** [comment]
It finally works! But actually I don't know why. 

My steps are here :
- Remove all certificates in your Firebase Project
- On Google Credentials, add 2 OAuth Clients with Android application type, using Upload and App Sign certificates from Google Play Console -> App integrity
- Add-back those signing certificates (Upload & App Sign) in Firebase Console (It shows error, but ignore it, still added correctly)

That's really weird, I haven't change anything from Unity side.

Thanks for the help by the way.

**Comment by coolishbee** [comment]
congratulations it works 🎉 

Even if you delete the certificate (ex. sha-1) from the firebase console, it doesn't matter because it exists in the Google API console. Among the generated titles, `auto generated` is that.

Thanks!
