### ISSUE TITLE
Logout from Apple.

### ISSUE THREAD

**Issue by yiki94** [coolishbee/universal-sdk-unity#24]
Hi @coolishbee I want to have a logout from Apple Login, to do this, I need to revoke token and require the client_id, client_secret etc. Does anyone know how to get the client_secret, token and client_id?

https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens

**Comment by coolishbee** [comment]
Hi,

client_id : The app's Bundle ID
client_secret : idToken in jwt format
token : It seems to be an authorizationCode.**(Sorry, Coming soon)**
