### ISSUE TITLE
Facebook Sign in

### ISSUE THREAD

**Issue by yiki94** [coolishbee/universal-sdk-unity#28]
I have read the documentation there's not much on Facebook. Can you explain more how to configure signing in with Facebook?

**Comment by coolishbee** [comment]
### Developers Page Registration

- Register application on Facebook Developers page. [Facebook Developer](https://developers.facebook.com/)
- Check the application ID after registration is completed.

<img width="662" alt="스크린샷 2023-11-17 오후 5 21 18" src="https://github.com/coolishbee/universal-sdk-unity/assets/20632507/2f6382be-27d2-4b73-bc5c-8b7b939dfaee">

### Facebook App Information Registration (Android)

- Check Facebook Android information for Android environment.
- Add Android platform on Facebook Developers page.
- Add Facebook Android information from Unity project to Facebook Android platform.

<img width="950" alt="스크린샷 2023-11-17 오후 5 55 00" src="https://github.com/coolishbee/universal-sdk-unity/assets/20632507/71283d90-33b0-4ae0-9b81-3f09dbbf3db6">

### Facebook App Information Registration (iOS)

- Add Facebook iOS platform on Developers Page.
- Enter iOS bundle ID information.

<img width="936" alt="스크린샷 2023-11-17 오후 5 56 18" src="https://github.com/coolishbee/universal-sdk-unity/assets/20632507/d48ebb89-1609-40da-842f-0f6777a41484">

**Comment by yiki94** [comment]
Does this mean I have to add Facebook Unity SDK into my project?

**Comment by coolishbee** [comment]
No. This is an explanation of configure signing in Facebook SDK. Facebook Unity SDK is built into Universal SDK.
