### ISSUE TITLE
 Could you include the field 'ServerAuthCode' in the Google sign-in result class?

### ISSUE THREAD

**Issue by guoweidong1987** [coolishbee/universal-sdk-unity#29]
Everything works fine; I only have a small request: Could you include the field 'ServerAuthCode' in the Google sign-in result class? I need it to sign in with the Playfab SDK. Thank you very much!

**Comment by coolishbee** [comment]
Coming soon. I will update ASAP.(with Apple authorizationCode)

**Comment by guoweidong1987** [comment]
That's great!
