### ISSUE TITLE
Multiple apps (using same account system)

### ISSUE THREAD

**Issue by MenesApps** [coolishbee/universal-sdk-unity#3]
Hi,
So I am working on a collection of apps that all use the same player account. I was previously using GameSparks but it is closing. 
Before I spend to much time implementing this, I'd like to know if this is something that will be handled correctly by this SDK :)
To make things simple, I have 3 games (Android & iOS) and one portal app that has all three games in it. More games are scheduled.
Each player uses the same account to login and all 4 apps use the same SHA1 signature. 
How hard would it be to use Google and Apple sign-in using this ?
Thanks a lot.

**Comment by coolishbee** [comment]
Hi,
Google and Apple sign-in difficulty individual differences, so it would be better to read the provided documentation.
A sample project is also prepared, so you can easily test it.

**For reference, GameSpark and this SDK have different feature.**
