### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.universal.sdk.unitywrapper.UniversalSDKWrapper

### ISSUE THREAD

**Issue by YoussefSayed34** [coolishbee/universal-sdk-unity#30]
This error happens when i try to call the signin for google

**Comment by coolishbee** [comment]
Are you activating R8 or Proguard when building?

- Project Settings > Player > Publishing Settings > Minify
![proguard01](https://github.com/coolishbee/universal-sdk-unity/assets/20632507/7bd7928a-0921-49c8-9be9-7594ec216cd3)
When obfuscated, classes cannot be found.

- After checking Custom Proguard File as follows, (Project Settings > Player > Publishing Settings > Custom Proguard file)
![proguard02](https://github.com/coolishbee/universal-sdk-unity/assets/20632507/7a327d3d-0382-46c2-bea3-90d504c1adda)

- Please add `-kepp class com.universal.sdk.unitywrapper.** {*;}` to proguard-user.txt
![proguard03](https://github.com/coolishbee/universal-sdk-unity/assets/20632507/54f5c147-da0e-4ec3-8b37-110381adb5c7)

You can also check it in the [Documents](https://chc3484.gitbook.io/sdk/unity-sdk/get-started/android-setup#proguard-settings) and [Troubleshooting](https://chc3484.gitbook.io/sdk/unity-sdk/trouble-shooting/android-proguard-classnotfoundexception) tabs.

**Comment by YoussefSayed34** [comment]
That worked!! Thanks for your help
