### ISSUE TITLE
Facebook Login Crashing

### ISSUE THREAD

**Issue by YoussefSayed34** [coolishbee/universal-sdk-unity#31]
## What did you do?

I tried to login with facebook

## What did you expect?

> facebook to login normally

## What happened actually?

after setting up the developer account and providing the app id in the launcher template the game crashes after i press the facebook login button google is working fine so it's a problem with facebook

## Your environment?

Latest Universal SDK version available on the asset store, 2021.3.17f1 Unity version, Android version 13, didn't test on IOS, I'm building 

## Screenshots or Log

> Sadly the game crashes without logging anything

**Comment by YoussefSayed34** [comment]
![ErrorFacebook](https://github.com/coolishbee/universal-sdk-unity/assets/149483945/a5208d33-b5c1-4187-826f-4ba519c2b550)
This is the error I'm getting from the crash

**Comment by coolishbee** [comment]
Since I can't check your config files, please test it out with the [demo project](https://github.com/coolishbee/universal-sdk-unity-demo).
Have you also set up `facebook_client_token`?
