### ISSUE TITLE
안드로이드 구글 로그인 오류

### ISSUE THREAD

**Issue by powerhyn** [coolishbee/universal-sdk-unity#32]
## What did you do?

안드로이드 기기에서 구글 로그인 시도

## What happened actually?

버튼을 눌러 로그인을 활성화 한 후 구글로 로그인이 완료된 후에 앱으로 돌아오면서 크래시가 발생합니다.

## Your environment?

에셋 스토어 최신 버전을 받아 사용하였고 유니티 2022.3.4f1 버전을 사용 중입니다.

<img width="957" alt="스크린샷 2023-12-12 오후 9 51 52" src="https://github.com/coolishbee/universal-sdk-unity/assets/8967710/e0347e55-1b36-467b-a006-921302b398c6">
<img width="258" alt="스크린샷 2023-12-12 오후 9 52 04" src="https://github.com/coolishbee/universal-sdk-unity/assets/8967710/82e634c7-93e3-43f1-9bf3-cf2a238d2dbc">

** 추가로 데모 프로젝트를 실행하여 테스트 하기 위해서는 어떤 절차가 필요한가요 ?

**Comment by coolishbee** [comment]
로그보니깐 난독화된 상태같아요 
혹시 프로가드 설정되있으신가요? #30 참고해보시겠어요?
데모 프로젝트는 별도 절차 없이 바로 실행가능합니다.

**Comment by powerhyn** [comment]
저도 #30 하고 같은 이슈가 처음에 있어서 프로가드를 세팅하고나서는 실행까지는 된 상태에서 에러가 발생하고 있는 상태입니다.
Target API Level을 지금 33으로 쓰고 있는데 이 부분이 이슈가 될 수 있을까요 ?

**Comment by coolishbee** [comment]
아무래도 안드로이드 라이브러리의 버전이 안맞는거 같아요
gradle 을 사용하시면
```
implementation 'io.github.coolishbee:universalsdk:3.0.8'
```
resolver 를 사용하시면
```
<androidPackage spec="io.github.coolishbee:universalsdk:3.0.8"/>
```
최신 버전인 3.0.8 이 맞는지 확인해주세요

**Comment by powerhyn** [comment]
@coolishbee 버전 문제가 맞네요 죄송합니다. 잘 작동 합니다 감사합니다 !! 👍
