### ISSUE TITLE
UniversalSDKSwift does not contain bitcode.

### ISSUE THREAD

**Issue by gofogo2** [coolishbee/universal-sdk-unity#33]
UniversalSDKSwift does not contain bitcode. 메세지가 뜨면서 XCODE에서 빌드가 안됩니다

개발환경 
XCODE 14.3 / IOS 16.3

bitcode 를 disable했지만, 그러면 framework not found 오류가떠서, 방법이 아닌거 같아서 혹시 이부분 해결법이 있을까요?

**Comment by coolishbee** [comment]
실제 오류 로그의 스샷, 로그 전체내용 그리고 unity 버전정보도 부탁드립니다.

추가로 테스트한 iOS 디바이스의 버전, minimum deployments 버전도 함께 기재해주세요.
