### ISSUE TITLE
안드로이드 애플 로그인 진행 중 이슈

### ISSUE THREAD

**Issue by powerhyn** [coolishbee/universal-sdk-unity#34]
## What did you do?

안드로이드에서 애플로그인 호출 후 애플 사이트에서 로그인 하고 리다이렉트 서버에서 리다이렉트 하는 부분까지 진행 된 후에
다시 앱 화면으로 돌아온 상황에서 어두운 딤드로 화면이 깔린 상태에서 진행이 되지 않습니다.
이 때 뒤로가기 버튼을 누르면

code : 7002, message: Callback intent is null 오류가 발생하고 있습니다.

어떤 부분이 잘못되었을까요 ?

아래는 redirect 시킨 url입니다.

coolish://callback?state={my_state}&code={my_code}&id_token={my_id_token}

서버로 들어온 문자열 그대로 coolish://callback? 뒤에 이어붙였을 때 위와 같은 형태로 만들어졌습니다.

## What did you expect?

> Please describe what you did expect to happen.

## What happened actually?

> Please describe what happened actually.

## Your environment?

> Some information of the environment in which the issue happened. Universal SDK version, Unity version, Android version, iOS version, etc.

**Comment by coolishbee** [comment]
테스트한 기기의 모델명과 `android os 버전` 그리고 `유니티 빌드환경`과 `min level`, `target api level` 은 어떻게 되나요?
가능하다면 테스트시 기록된 adb log 내용도 첨부가 가능하면 부탁드립니다.

[데모 프로젝트](https://github.com/coolishbee/universal-sdk-unity-demo)로 테스트해보시고 비교해보는 것도 도움이 될 수 있습니다.

**Comment by powerhyn** [comment]
@coolishbee 네 데모 프로젝트에서 테스트를 해봤을 때 작동을 하길래 어떤 부분이 다른가 비교해보았는데요 Publishing Settings에서 Minify상태가 다른것을 확인해였습니다.
해당 부분을 데모 프로젝트에서도 활성화 후에 작동을 해보니까 잘 작동하던 데모 프로젝트에서도 같은 현상이 발생 하더라구요
요 부분 난독화로 인한 프로가드 설정으로 해결되는 부분이라고 생각 했었는데 데모 프로젝트 상태에서도 추가로 설정해야 하는 부분이 있을까요 ?

**Comment by coolishbee** [comment]
Minify 의 체크박스를 활성화하셨고 
proguard-user.txt 에는 `-keep class com.universal.sdk.unitywrapper.** { *; }`로 설정하셨는데
이슈가 발생하신다는 거죠?

1. 본인 프로젝트에서도 난독화 기능을 해제하시면 애플로그인이 정상적으로 작동되나요?
2. 일단 redirect 시키신 url 은 맞습니다.
3. 서버에서 리다이렉트 후에 클라이언트에서 성공이든 실패든 콜백처리가 안됐다면 adb 로 로그를 봐야할 것 같아요.
4. 그리고 애플로그인이 모바일환경에 웹을 띄우는 방식이라 환경을 타기 때문에 테스트한 기기 정보와 android os 버전을 제공해주셔야 해요.

**Comment by powerhyn** [comment]
@coolishbee 
1. 네 맞습니다 난독화 해제시 제 프로젝트와 데모 프로젝트 모두에서 잘 작동 하는 상황입니다.
3. 이 부분에 조금 애매한데요 저도 처음에 로그를 보고 문제가 무엇인지 파악해 보려고 했는데 정확히 잘 모르겠더라구요.. 혹시 몰라 로그는 아래쪽에 추가로 첨부하도록 하겠습니다.
4. SM-G977N(안드로이드 12버전),  SM-S916N(안드로이드 14 버전) 두 기기에서 테스트 진행 해보았습니다.

새해 복 많이 받으세요 !!


- log
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of main
2023/12/30 15:56:51.288 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] handleAppVisibility mAppVisible=false visible=true
2023/12/30 15:56:51.298 9878 10138 Debug OpenGLRenderer setSurface called with nullptr
2023/12/30 15:56:51.328 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] Relayout returned: old=(104,0,2280,1080) new=(104,0,2280,1080) req=(2176,1080)4 dur=30 res=0x1 s={false 0} ch=false fn=-1
2023/12/30 15:56:51.329 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] handleAppVisibility mAppVisible=false visible=true
2023/12/30 15:56:51.329 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] handleAppVisibility mAppVisible=false visible=true
2023/12/30 15:56:51.330 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] stopped(false) old=true
2023/12/30 15:56:51.330 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] stopped(false) old=true
2023/12/30 15:56:51.331 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] stopped(false) old=true
2023/12/30 15:56:51.335 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] stopped(false) old=false
2023/12/30 15:56:51.335 9878 9878 Info DecorView notifyKeepScreenOnChanged: keepScreenOn=false
2023/12/30 15:56:51.336 9878 10138 Debug OpenGLRenderer setSurface called with nullptr
2023/12/30 15:56:51.339 9878 10156 Info ViewRootImpl@5102015[AppleLoginActivity] Resizing android.view.ViewRootImpl@f3a52c4: frame=[104,0][2280,1080] reportDraw=true forceLayout=true backDropFrame=Rect(0, 0 - 2176, 1080)
2023/12/30 15:56:51.343 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] Relayout returned: old=(104,0,2280,1080) new=(104,0,2280,1080) req=(2176,1080)0 dur=5 res=0x7 s={true 2864728992} ch=true fn=-1
2023/12/30 15:56:51.344 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11442 android.view.ViewRootImpl.performTraversals:4198 android.view.ViewRootImpl.doTraversal:2924 
2023/12/30 15:56:51.344 9878 9878 Debug ViewRootImpl@5102015[AppleLoginActivity] Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
2023/12/30 15:56:51.344 9878 9878 Debug ViewRootImpl@5102015[AppleLoginActivity] Creating frameCompleteCallback
2023/12/30 15:56:51.344 9878 10138 Debug OpenGLRenderer eglCreateWindowSurface
2023/12/30 15:56:51.345 9878 10147 Debug ViewRootImpl@5102015[AppleLoginActivity] Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
2023/12/30 15:56:51.352 9878 10138 Debug ViewRootImpl@5102015[AppleLoginActivity] Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
2023/12/30 15:56:51.353 9878 10138 Debug OpenGLRenderer setSurface called with nullptr
2023/12/30 15:56:51.356 9878 10156 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Resizing android.view.ViewRootImpl@8a525ad: frame=[104,0][2280,1080] reportDraw=true forceLayout=true backDropFrame=Rect(0, 0 - 2176, 1080)
2023/12/30 15:56:51.358 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Relayout returned: old=(104,0,2280,1080) new=(104,0,2280,1080) req=(2176,1080)0 dur=4 res=0x7 s={true 3892264768} ch=true fn=-1
2023/12/30 15:56:51.358 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11442 android.view.ViewRootImpl.performTraversals:4198 android.view.ViewRootImpl.doTraversal:2924 
2023/12/30 15:56:51.358 9878 9878 Debug ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
2023/12/30 15:56:51.358 9878 9878 Debug ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Creating frameCompleteCallback
2023/12/30 15:56:51.358 9878 10138 Debug OpenGLRenderer eglCreateWindowSurface
2023/12/30 15:56:51.359 9878 10148 Debug ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
2023/12/30 15:56:51.371 9878 10138 Debug ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
2023/12/30 15:56:51.372 9878 9878 Info SurfaceView@e3f3f04 onWindowVisibilityChanged(0) false com.unity3d.player.a{e3f3f04 VFE...... .F....I. 0,0-2280,1080 #7f0800e3 app:id/unitySurfaceView aid=1073741824} of ViewRootImpl@b3b04f7[UnityPlayerActivity]
2023/12/30 15:56:51.372 9878 9878 Debug SurfaceView@e3f3f04 updateSurface: surface is not valid
2023/12/30 15:56:51.374 9878 10156 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] Resizing android.view.ViewRootImpl@c1ceba6: frame=[0,0][2280,1080] reportDraw=true forceLayout=true backDropFrame=Rect(0, 0 - 2280, 1080)
2023/12/30 15:56:51.376 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] Relayout returned: old=(0,0,2280,1080) new=(0,0,2280,1080) req=(2280,1080)0 dur=3 res=0x7 s={true 3892103568} ch=true fn=-1
2023/12/30 15:56:51.376 9878 9878 Info SurfaceView@e3f3f04 windowStopped(false) true com.unity3d.player.a{e3f3f04 VFE...... .F....I. 0,0-2280,1080 #7f0800e3 app:id/unitySurfaceView aid=1073741824} of ViewRootImpl@b3b04f7[UnityPlayerActivity]
2023/12/30 15:56:51.378 9878 9878 Info SurfaceView@e3f3f04 pST: sr = Rect(0, 0 - 2280, 1080) sw = 2280 sh = 1080
2023/12/30 15:56:51.378 9878 9878 Info SurfaceView@e3f3f04 onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
2023/12/30 15:56:51.378 9878 9878 Info SurfaceView@e3f3f04 pST: mTmpTransaction.apply, mTmpTransaction = android.view.SurfaceControl$Transaction@adbebda
2023/12/30 15:56:51.378 9878 9878 Info SurfaceView@e3f3f04 updateSurface: mVisible = true mSurface.isValid() = true
2023/12/30 15:56:51.378 9878 9878 Info SurfaceView@e3f3f04 updateSurface: mSurfaceCreated = false surfaceChanged = true visibleChanged = true
2023/12/30 15:56:51.378 9878 9878 Info SurfaceView@e3f3f04 surfaceCreated 1 #1 com.unity3d.player.a{e3f3f04 VFE...... .F....I. 0,0-2280,1080 #7f0800e3 app:id/unitySurfaceView aid=1073741824}
2023/12/30 15:56:51.378 9878 9878 Info SurfaceView@e3f3f04 surfaceChanged (2280,1080) 1 #1 com.unity3d.player.a{e3f3f04 VFE...... .F....I. 0,0-2280,1080 #7f0800e3 app:id/unitySurfaceView aid=1073741824}
2023/12/30 15:56:51.378 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1375 android.view.SurfaceView.setWindowStopped:383 android.view.SurfaceView.surfaceCreated:2051 
2023/12/30 15:56:51.379 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:599 android.view.SurfaceView.performDrawFinished:586 android.view.SurfaceView.$r8$lambda$st27mCkd9jfJkTrN_P3qIGKX6NY:0 
2023/12/30 15:56:51.379 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] [DP] rdf()
2023/12/30 15:56:51.379 9878 9878 Debug ViewRootImpl@b3b04f7[UnityPlayerActivity] reportDrawFinished (fn: -1) 
2023/12/30 15:56:51.379 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11442 android.view.ViewRootImpl.performTraversals:4198 android.view.ViewRootImpl.doTraversal:2924 
2023/12/30 15:56:51.379 9878 9878 Debug ViewRootImpl@b3b04f7[UnityPlayerActivity] Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
2023/12/30 15:56:51.385 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] [DP] pdf(0) 1 android.view.ViewRootImpl.performDraw:5212 android.view.ViewRootImpl.performTraversals:4217 android.view.ViewRootImpl.doTraversal:2924 
2023/12/30 15:56:51.385 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] [DP] rdf()
2023/12/30 15:56:51.385 9878 9878 Debug ViewRootImpl@b3b04f7[UnityPlayerActivity] reportDrawFinished (fn: -1) 
2023/12/30 15:56:51.385 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:5000 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
2023/12/30 15:56:51.385 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] [DP] rdf()
2023/12/30 15:56:51.385 9878 9878 Debug ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] reportDrawFinished (fn: -1) 
2023/12/30 15:56:51.385 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:5000 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
2023/12/30 15:56:51.385 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] [DP] rdf()
2023/12/30 15:56:51.385 9878 9878 Debug ViewRootImpl@5102015[AppleLoginActivity] reportDrawFinished (fn: -1) 
2023/12/30 15:56:51.385 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] handleResized, msg = 5 frames=ClientWindowFrames{frame=[104,0][2280,1080] display=[104,0][2280,1080] backdrop=[0,0][2176,1080]} forceNextWindowRelayout=true displayId=0 frameChanged=false backdropFrameChanged=false configChanged=false displayChanged=false mNextDrawUseBlastSync=false mergedConfiguration={mGlobalConfig={1.1 ?mcc?mnc [ko_KR] ldltr sw411dp w780dp h387dp 420dpi nrml long land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2280, 1080) mAppBounds=Rect(104, 0 - 2154, 1080) mMaxBounds=Rect(0, 0 - 2280, 1080) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} s.14509 fontWeightAdjustment=0 ff=0 bf=0 bts=0 desktop/d dm/n dc/d ?dcui ?dcaf enb/d themeSeq=0} mOverrideConfig={1.1 ?mcc?mnc [ko_KR] ldltr sw411dp w780dp h387dp 420dpi nrml long land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2280, 1080) mAppBounds=Rect(104, 0 - 2154, 1080) mMaxBounds=Rect(0, 0 - 2280, 1080) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} s.3 fontWeightAdjustment=0 ff=0 bf=0 bts=0 desktop/d dm/n dc/d ?dcui ?dcaf enb/d themeSeq=0}}
2023/12/30 15:56:51.385 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11442 android.view.ViewRootImpl.handleResized:2235 android.view.ViewRootImpl.access$1200:303 
2023/12/30 15:56:51.389 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] Relayout returned: old=(104,0,2280,1080) new=(104,0,2280,1080) req=(2176,1080)0 dur=3 res=0x3 s={true 2864728992} ch=false fn=2
2023/12/30 15:56:51.389 9878 9878 Debug ViewRootImpl@5102015[AppleLoginActivity] Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
2023/12/30 15:56:51.389 9878 9878 Debug ViewRootImpl@5102015[AppleLoginActivity] Creating frameCompleteCallback
2023/12/30 15:56:51.389 9878 10138 Debug OpenGLRenderer setSurface() destroyed EGLSurface
2023/12/30 15:56:51.389 9878 10138 Debug OpenGLRenderer destroyEglSurface
2023/12/30 15:56:51.390 9878 10138 Debug OpenGLRenderer eglCreateWindowSurface
2023/12/30 15:56:51.390 9878 10147 Debug ViewRootImpl@5102015[AppleLoginActivity] Received frameDrawingCallback frameNum=2. Creating transactionCompleteCallback=false
2023/12/30 15:56:51.393 9878 10138 Debug ViewRootImpl@5102015[AppleLoginActivity] Received frameCompleteCallback  lastAcquiredFrameNum=2 lastAttemptedDrawFrameNum=2
2023/12/30 15:56:51.407 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:5000 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
2023/12/30 15:56:51.407 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] [DP] rdf()
2023/12/30 15:56:51.407 9878 9878 Debug ViewRootImpl@5102015[AppleLoginActivity] reportDrawFinished (fn: 2) 
2023/12/30 15:56:51.407 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] handleResized, msg = 5 frames=ClientWindowFrames{frame=[104,0][2280,1080] display=[104,0][2280,1080] backdrop=[0,0][2176,1080]} forceNextWindowRelayout=true displayId=0 frameChanged=false backdropFrameChanged=false configChanged=false displayChanged=false mNextDrawUseBlastSync=false mergedConfiguration={mGlobalConfig={1.1 ?mcc?mnc [ko_KR] ldltr sw411dp w780dp h387dp 420dpi nrml long land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2280, 1080) mAppBounds=Rect(104, 0 - 2154, 1080) mMaxBounds=Rect(0, 0 - 2280, 1080) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} s.14509 fontWeightAdjustment=0 ff=0 bf=0 bts=0 desktop/d dm/n dc/d ?dcui ?dcaf enb/d themeSeq=0} mOverrideConfig={1.1 ?mcc?mnc [ko_KR] ldltr sw411dp w780dp h387dp 420dpi nrml long land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2280, 1080) mAppBounds=Rect(104, 0 - 2154, 1080) mMaxBounds=Rect(0, 0 - 2280, 1080) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} s.3 fontWeightAdjustment=0 ff=0 bf=0 bts=0 desktop/d dm/n dc/d ?dcui ?dcaf enb/d themeSeq=0}}
2023/12/30 15:56:51.407 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11442 android.view.ViewRootImpl.handleResized:2235 android.view.ViewRootImpl.access$1200:303 
2023/12/30 15:56:51.407 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] handleResized, msg = 5 frames=ClientWindowFrames{frame=[0,0][2280,1080] display=[0,0][2280,1080] backdrop=[0,0][2280,1080]} forceNextWindowRelayout=true displayId=0 frameChanged=false backdropFrameChanged=false configChanged=false displayChanged=false mNextDrawUseBlastSync=false mergedConfiguration={mGlobalConfig={1.1 ?mcc?mnc [ko_KR] ldltr sw411dp w780dp h387dp 420dpi nrml long land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2280, 1080) mAppBounds=Rect(104, 0 - 2154, 1080) mMaxBounds=Rect(0, 0 - 2280, 1080) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} s.14509 fontWeightAdjustment=0 ff=0 bf=0 bts=0 desktop/d dm/n dc/d ?dcui ?dcaf enb/d themeSeq=0} mOverrideConfig={1.1 ?mcc?mnc [ko_KR] ldltr sw411dp w780dp h387dp 420dpi nrml long land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2280, 1080) mAppBounds=Rect(104, 0 - 2154, 1080) mMaxBounds=Rect(0, 0 - 2280, 1080) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} s.7 fontWeightAdjustment=0 ff=0 bf=0 bts=0 desktop/d dm/n dc/d ?dcui ?dcaf enb/d themeSeq=0}}
2023/12/30 15:56:51.408 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11442 android.view.ViewRootImpl.handleResized:2235 android.view.ViewRootImpl.access$1200:303 
2023/12/30 15:56:51.430 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Relayout returned: old=(104,0,2280,1080) new=(104,0,2280,1080) req=(2176,1080)0 dur=1 res=0x1 s={true 3892264768} ch=false fn=3
2023/12/30 15:56:51.430 9878 9878 Debug ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
2023/12/30 15:56:51.430 9878 9878 Debug ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Creating frameCompleteCallback
2023/12/30 15:56:51.430 9878 10138 Debug OpenGLRenderer setSurface() destroyed EGLSurface
2023/12/30 15:56:51.430 9878 10138 Debug OpenGLRenderer destroyEglSurface
2023/12/30 15:56:51.430 9878 10138 Debug OpenGLRenderer eglCreateWindowSurface
2023/12/30 15:56:51.431 9878 10148 Debug ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Received frameDrawingCallback frameNum=3. Creating transactionCompleteCallback=false
2023/12/30 15:56:51.437 9878 10138 Debug ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] Received frameCompleteCallback  lastAcquiredFrameNum=3 lastAttemptedDrawFrameNum=3
2023/12/30 15:56:51.439 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] Relayout returned: old=(0,0,2280,1080) new=(0,0,2280,1080) req=(2280,1080)0 dur=2 res=0x1 s={true 3892103568} ch=false fn=3
2023/12/30 15:56:51.439 9878 9878 Debug ViewRootImpl@b3b04f7[UnityPlayerActivity] Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
2023/12/30 15:56:51.448 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] [DP] pdf(0) 1 android.view.ViewRootImpl.performDraw:5212 android.view.ViewRootImpl.performTraversals:4217 android.view.ViewRootImpl.doTraversal:2924 
2023/12/30 15:56:51.448 9878 9878 Info ViewRootImpl@b3b04f7[UnityPlayerActivity] [DP] rdf()
2023/12/30 15:56:51.448 9878 9878 Debug ViewRootImpl@b3b04f7[UnityPlayerActivity] reportDrawFinished (fn: 3) 
2023/12/30 15:56:51.449 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:5000 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
2023/12/30 15:56:51.449 9878 9878 Info ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] [DP] rdf()
2023/12/30 15:56:51.449 9878 9878 Debug ViewRootImpl@e3ae788[UniversalSdkWrapperActivity] reportDrawFinished (fn: 3) 
2023/12/30 15:56:51.449 9878 9878 Info ViewRootImpl@5102015[AppleLoginActivity] MSG_WINDOW_FOCUS_CHANGED 1 1
2023/12/30 15:56:51.449 9878 9878 Debug InputMethodManager startInputInner - Id : 0
2023/12/30 15:56:51.449 9878 9878 Info InputMethodManager startInputInner - mService.startInputOrWindowGainedFocus
2023/12/30 15:56:51.554 9878 9878 Debug InsetsSourceConsumer ensureControlPosition: Point(2154, 0) for ITYPE_NAVIGATION_BAR on com.mong.mongGameApp/io.github.coolishbee.auth.AppleLoginActivity from android.view.InsetsSourceConsumer.notifyAnimationFinished:384
2023/12/30 15:56:51.554 9878 9878 Debug InsetsSourceConsumer ensureControlPosition: Point(0, 0) for ITYPE_STATUS_BAR on com.mong.mongGameApp/io.github.coolishbee.auth.AppleLoginActivity from android.view.InsetsSourceConsumer.notifyAnimationFinished:384
2023/12/30 15:57:12.486 9878 9883 Info mong.mongGameApp Thread[6,tid=9883,WaitingInMainSignalCatcherLoop,Thread*=0xe758fc10,peer=0x130401f0,"Signal Catcher"]: reacting to signal 10
2023/12/30 15:57:12.486 9878 9883 Info mong.mongGameApp 
2023/12/30 15:57:12.486 9878 9883 Info mong.mongGameApp SIGUSR1 forcing GC (no HPROF) and profile save
2023/12/30 15:57:12.523 9878 9883 Info mong.mongGameApp Explicit concurrent copying GC freed 9131(567KB) AllocSpace objects, 2(104KB) LOS objects, 68% free, 2806KB/8950KB, paused 304us,78us total 36.782ms

**Comment by coolishbee** [comment]
proguard-user.txt 에 `-keep class io.github.coolishbee.** { *; }` 를 추가해보시고
그래도 안되면 unity 버전을 메이저로 올리거나 r8 옵션으로도 한번 테스트 해보시겠어요?

새해복 많이 받으세요!^^
감사합니다

**Comment by powerhyn** [comment]
-keep class io.github.coolishbee.** { *; }
추가 후 정상 작동 합니다 감사합니다 :)

**Comment by coolishbee** [comment]
좋은 이슈 열어주셔서 감사합니다 😄 
`com.universal.sdk.unitywrapper` class 는 인터페이스며 `io.github.coolishbee` 가 실제 구현부 class 거든요.

minify 옵션 활성화시 API 호출은 되는데 OnNewIntent 가 수신을 못하는 상황이었던 거 같습니다.
