### ISSUE TITLE
On iPhone,  google sign in, ResultHandler only returns LoginSuccess when click cancle after once login.

### ISSUE THREAD

**Issue by zkunsang** [coolishbee/universal-sdk-unity#36]
## What did you do?

> I've signed in with google login on iPhone device. and logout. 
login and it shows native popup "cancel", "continue"
and I canceled but it signed in with previous login info.  \
\
and after click "continue" and it show's google login list
and click cancel button it placed top left.
but it signed in with previous login info

## What did you expect?

> I want to got Login fail when I click cancel button after once signed in and logout

## What happened actually?

> 

## Your environment?

> universal sdk version 1.2.7, 1.2.8, 
Unity 2021.3.33f1
iOS 17.2.1

## Screenshots or Log

>

**Comment by coolishbee** [comment]
안녕하세요, 한국분이신거 같으니 한국말로 답변드릴게요:)
iOS 에서 구글로그인에 성공 이후에는 취소처리가 안된다는 말씀이신거죠?

빠른시일내에 업데이트될 수 있게 도와드리겠습니다!

**Comment by zkunsang** [comment]
넵 감사합니다 :)

**Comment by coolishbee** [comment]
@zkunsang [에셋스토어](https://assetstore.unity.com/packages/tools/integration/universal-sdk-204843)에 최신버전으로 업데이트 되었습니다!

**Comment by zkunsang** [comment]
감사합니다!
