### ISSUE TITLE
[안드로이드] 인앱결제v4로 올라가게되면서 버전을 올렸을때 충돌이 나는듯합니다.

### ISSUE THREAD

**Issue by RookieKevin** [coolishbee/universal-sdk-unity#4]
com.google.android.play.billingclient.version@value value=(4.0.0) from [:billing-4.0.0:] 

[com.android.billingclient:billing:3.0.3]

해당 부분이 충돌나는거같네요

**Comment by RookieKevin** [comment]
결제 관련 부분만 따로 뺄 수 있으면 좋을거같아요!! ㅎㅎ 감사합니다!

**Comment by coolishbee** [comment]
피드백 감사합니다!^^
현재 v4 업데이트 준비중입니다. 그리고 결제기능을 제외한 sdk 도 별도로 준비중입니다.
