### ISSUE TITLE
iOS Google Login Fail

### ISSUE THREAD

**Issue by hendlake8** [coolishbee/universal-sdk-unity#40]
![failgoogle](https://github.com/coolishbee/universal-sdk-unity/assets/5662568/18b52bfe-46c9-4388-95de-8f349b618b51)
I've configured as shown in the picture in UniversalSDKSettings, but when trying to do Google login on iOS, it says 'googleClientID is empty'. Is there anything else I need to set?

**Comment by coolishbee** [comment]
Did OnPostProcessBuild() work properly? 
Please check it out. Sometimes unity editor bugs occur.

**Comment by hendlake8** [comment]
![sdkFail](https://github.com/coolishbee/universal-sdk-unity/assets/5662568/8c4cd9bb-6530-4e0c-8e44-59bdf9df3621)
OnPostProcessBuild() is being called correctly. However, in the null check part of the instance in the UniversalSDKSettings load syntax, the null check was not properly done using the ReferenceEquals function. So, I changed it to 'instance == null', and after doing so, I confirmed that the clientID was properly inserted into the Info.plist file and Google login is now working.

**Comment by hendlake8** [comment]
Do I need to include the ReversedClientID in the info.plist file even though there is no usage of it?

**Comment by coolishbee** [comment]
> ![sdkFail](https://private-user-images.githubusercontent.com/5662568/319497134-8c4cd9bb-6530-4e0c-8e44-59bdf9df3621.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTg3MjUsIm5iZiI6MTcxMjIxODQyNSwicGF0aCI6Ii81NjYyNTY4LzMxOTQ5NzEzNC04YzRjZDliYi02NTMwLTRlMGMtOGU0NC01OWJkZjlkZjM2MjEuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMDgxMzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhhZjVjNDY1ZTJhMjkyZWNkZGUyMzM1NjFiMzM3NzA5NDdhNWE2YTAwYzE3YmZjN2RhODU2N2QwMWY1ZmJhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qP2qbNjT98fJjuVh8rlWpZ5F-NORGq9blamMvYvC9hI) OnPostProcessBuild() is being called correctly. However, in the null check part of the instance in the UniversalSDKSettings load syntax, the null check was not properly done using the ReferenceEquals function. So, I changed it to 'instance == null', and after doing so, I confirmed that the clientID was properly inserted into the Info.plist file and Google login is now working.

Thank you I will fix the bug soon

**Comment by coolishbee** [comment]
> Do I need to include the ReversedClientID in the info.plist file even though there is no usage of it?

If you do not use iOS Google login, you can leave it blank. If not, it becomes a requirement.

**Comment by coolishbee** [comment]
Released as unity sdk 1.2.10
