### ISSUE TITLE
IOS에서 구글 로그인 시 AuthCode가 비어있는 경우

### ISSUE THREAD

**Issue by HwangTaeJun** [coolishbee/universal-sdk-unity#43]
IOS에서 구글 로그인 시 idToken, userId 등의 데이터는 잘 오지만 authCode 값이 "" 전달되고 있습니다.
해당 이슈의 원인과 해결 방법을 알고 싶습니다.

**Comment by coolishbee** [comment]
serverauthcode는 사용자가 처음 로그인할  때에만 전송됩니다. 매번 구글로그인할 때마다 serverauthcode가 전송되진 않습니다. https://security.google.com/settings/security/permissions 로 이동하여 앱의 자격 증명을 제거하면 서버 인증 코드를 받게 됩니다.

**Comment by HwangTaeJun** [comment]
> serverauthcode는 사용자가 처음 로그인할 때에만 전송됩니다. 매번 구글로그인할 때마다 serverauthcode가 전송되진 않습니다. https://security.google.com/settings/security/permissions 로 이동하여 앱의 자격 증명을 제거하면 서버 인증 코드를 받게 됩니다.
> 
> stackoverflow 글을 공유한 것인데 만약 해결이 안되시면 회신주세요:)

해당 과정을 거쳐 자격 증명을 제거 해도 같은 현상이 발생합니다!

**Comment by coolishbee** [comment]
serverauthcode 를 매번 받기 위해서는 [OAuth 서버 클라이언트 id](https://developers.google.com/identity/sign-in/ios/start-integrating?hl=ko#server_client_id) 가 필요합니다.

![스크린샷 2024-05-12 오후 11 48 36](https://github.com/coolishbee/universal-sdk-unity/assets/20632507/ef1b8342-e6bf-4604-ac59-ac75dfc08bde)
![스크린샷 2024-05-12 오후 11 48 48](https://github.com/coolishbee/universal-sdk-unity/assets/20632507/730baf80-1945-4b3f-bafc-86bf4873a6f2)

iOS 빌드시 Info.plist 에 아래 내용을 추가해주세요.
Key : GIDServerClientID
Value : 웹 애플리케이션 유형의 OAuth 클라이언트 ID

추가 업데이트 없이 해보실 수 있는 방법입니다.
현재 없는 기능이라서 앞으로 업데이트에 반영하겠습니다. 좋은 의견 올려주셔서 감사합니다:)

**Comment by coolishbee** [comment]
에셋스토어에 배포가 완료되었습니다. 😄
