### ISSUE TITLE
apple nested framework issue

### ISSUE THREAD

**Issue by alexsluch** [coolishbee/universal-sdk-unity#44]
<img width="748" alt="Untitled 56" src="https://github.com/coolishbee/universal-sdk-unity/assets/47083996/28539aaf-7566-4ed9-9bdd-f9e2b0fde3da">

Tried to upload on appstore

**Comment by coolishbee** [comment]
Sorry, I'm looking for the cause.
It seemed like the Facebook SDK was the cause, so I isolated it. Could you try applying each framework in the zip file?
[Archive framework.zip](https://github.com/coolishbee/universal-sdk-unity/files/15241438/Archive.framework.zip)
