### ISSUE TITLE
Universal SDK "unsupported architecture" in Xcode

### ISSUE THREAD

**Issue by episodicJaycee** [coolishbee/universal-sdk-unity#45]
## What did you do?

I installed the Universal SDK per the docs (not very clear by the way). Created an iOS Xcode Project from Unity for Simulator and Device. Opened the project in Xcode. Hit build (simulator and device).

## What did you expect?

The project would build to simulator/device.

## What happened actually?

The build failed with the following error
<img width="2672" alt="Screenshot 2024-05-07 at 2 32 25 PM" src="https://github.com/coolishbee/universal-sdk-unity/assets/154370341/1b672e61-7a80-41bc-9e65-188666a71a50">
<img width="2672" alt="Screenshot 2024-05-07 at 2 48 26 PM" src="https://github.com/coolishbee/universal-sdk-unity/assets/154370341/4aad7ea4-a0be-435b-aa11-b5e051b9f729">

## Your environment?

Unity 2022.3.27f1
iOS 17.4 simulator/device
Universal SDK 1.3.0
Xcode 15.3

## Screenshots or Log
Screenshots included above ;)

**Comment by coolishbee** [comment]
sorry 😢 The simulator architecture is not yet supported.
I have plans to apply soon :)

**Comment by episodicJaycee** [comment]
Hmmm, ok. I got it built to my device but then I get this error

<img width="1159" alt="Screenshot 2024-05-07 at 4 25 55 PM" src="https://github.com/coolishbee/universal-sdk-unity/assets/154370341/d64a7bc0-d564-4e8d-841b-4ab21d504d37">

I then followed the troubleshooting in the docs, but those settings were already set [https://chc3484.gitbook.io/sdk/unity-sdk/trouble-shooting/universalsdk.framework-load-failure-when-running-app](url)

**Comment by episodicJaycee** [comment]
Any idea why I’d be getting this issue? I can’t seem to figure it out? I finally got the app to build properly to device, since the simulator is not available yet as you mentioned.
￼

**Comment by coolishbee** [comment]
It's clear why the library wasn't loaded. 
This is because it was not referenced during build. 
There is no other way to explain it.

If the library is not loaded, can you try deleting the build folder and trying again cleanly, or try adding the library manually?
(A new version has been released, please try it.)

**Comment by episodicJaycee** [comment]
Hey James,

I saw that you released the update to 1.3.1 and updated. That seemed to do the trick. Now I’m stuck on other issues, but not to do with Universal. Thanks!!!
