### ISSUE TITLE
안드로이드에서 애플로그인 진행시 로그인 성공 후 플레이 스토어로 넘어갑니다.

### ISSUE THREAD

**Issue by mwdev-3d** [coolishbee/universal-sdk-unity#49]
## What did you do?

> 안드로이드에서 애플로그인 진행시 로그인 성공후 플레이 스토어로 넘어가고, 앱으로 다시 돌아오지 않습니다.

## What did you expect?

> 로그인 성공후에 앱이 실행되거나 앱을 실행하시겠습니까를 물어야 합니다.

## What happened actually?

> 앱의 플레이 스토어로 넘어갑니다.

## Your environment?

> 갤럭시 S7에서 진행했습니다(저사양 지원을 위해서). 안드로이드 버전은 8.0.0입니다.
Unity version : 2022.3.34
UniversalSDK version : 1.3.
엡의 1.0버전은 플레이스토어에 내부 테스트로 출시 되어있는 상태임
테스트 중인 앱의 버전은 1.1이고 내부 테스트로 올라가있지 않은 상태임

## Screenshots or Log

> It would be appreciated if you can provide a screenshot or log that i can infer the issue.

**Comment by coolishbee** [comment]
1. 로그인 성공후 [Redirect 서버]()단에서 애플서버로부터 Request 를 받으셨나요?
1-1. 만약 수신를 하지 못했다면 관련 [설정](https://chc3484.gitbook.io/sdk/v/ko/console-guide/apple-login/android)을 확인해주세요.
1-2. 수신이 정상적으로 됐다면 Redirect에 `coolish://callback?`로 시작하는 문자열이 들어갔는지 확인해주세요.

**Comment by mwdev-3d** [comment]
아 coolish 로 안적혀있었네요 덕분에 해결했습니다 감사합니다.
