### ISSUE TITLE
Google login with API level 34 not working.

### ISSUE THREAD

**Issue by YoussefSayed34** [coolishbee/universal-sdk-unity#51]
## What did you do?

> Build the app with API level 34 and try google login

## What did you expect?

> Google login working.

## What happened actually?

> No login working, having no response at all.

## Your environment?

> Unity.2021.3.34f1 - API level 34 - UniversalSDK version: 1.3.3

## Screenshots or Log

> AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
10/22 13:57:57.807 30193 30268 Error Unity java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
10/22 13:57:57.807 30193 30268 Error Unity 	at com.universal.sdk.unitywrapper.UniversalSdkWrapper.login(SourceFile:3)
10/22 13:57:57.807 30193 30268 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
10/22 13:57:57.807 30193 30268 Error Unity 	at com.unity3d.player.UnityPlayer.access$500(Unknown Source:0)
10/22 13:57:57.807 30193 30268 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:114)
10/22 13:57:57.807 30193 30268 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
10/22 13:57:57.807 30193 30268 Error Unity 	at android.os.Looper.loopOnce(Looper.java:226)
10/22 13:57:57.807 30193 30268 Error Unity 	at android.os.Looper.loop(Looper.java:313)
10/22 13:57:57.807 30193 30268 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
10/22 13:57:57.807 30193 30268 Error Unity Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
10/22 13:57:57.807 30193 30268 Error Unity 	... 8 more
10/22 13:57:57.807 30193 30268 Error Unity   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
10/22 13:57:57.807 30193 30268 Error Unity   at UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0

**Comment by coolishbee** [comment]
1. Do you have [ProGuard](https://chc3484.gitbook.io/sdk/unity-sdk/get-started/android-setup#proguard-settings) set up?
2. Does it work with API level 33?

**Comment by YoussefSayed34** [comment]
1. We use ProGuard set up is properly done.
2. It does work with API level 33 .. but due to recent google publishing rules we need to update to at least API 34

**Comment by coolishbee** [comment]
- Have you recently changed your Unity version? - If so, check the settings for your Gradle version.

**Comment by coolishbee** [comment]
- What is the current [Unity gradle version?](https://docs.unity3d.com/2021.3/Documentation/Manual/android-gradle-overview.html) You can find out by checking the path.
> /Applications/Unity/Hub/Editor/2022.3.41f1/PlaybackEngines/AndroidPlayer/Tools/gradle/lib
- Is `maven { url 'https://jitpack.io' }` added to settingsTemplate.gradle?
    - Please refer to the [setup guide](https://chc3484.gitbook.io/sdk/unity-sdk/get-started/android-setup/jitpack-to-migration#step-1.-add-it-in-your-settingstemplate.gradle-in-project)
    - If settingsTemplate.gradle is not supported, add it to mainTemplate.gradle

**Comment by YoussefSayed34** [comment]
- This is the gradle version we use: 6.1.1
- I'll add the previous line, but do I need to upgrade the gradle version ?

**Comment by coolishbee** [comment]
No, you don't need to upgrade gradle version. The repository location has recently changed, so you need to add `jitpack.io`.

**Comment by YoussefSayed34** [comment]
I followed the setup guide but was unable to build due to gradle errors,
Here is the full log (sorry about this horrible sight):

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2021.3.34f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2021.3.34f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-6.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > AAPT2 aapt2-4.0.1-6197926-windows Daemon #0: Unexpected error during link, attempting to stop daemon.
     This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[

> Configure project :launcher
WARNING: The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8

> Task :launcher:preBuild UP-TO-DATE
> Task :launcher:extractProguardFiles UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseAidl NO-SOURCE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :launcher:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseManifest UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseLibraryResources UP-TO-DATE
> Task :unityLibrary:processReleaseManifest UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:compileReleaseLibraryResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseJavaWithJavac UP-TO-DATE
> Task :launcher:mergeReleaseResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibCompileToJarRelease UP-TO-DATE
> Task :launcher:processReleaseManifest UP-TO-DATE
> Task :unityLibrary:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:bundleLibCompileToJarRelease UP-TO-DATE
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseAssets UP-TO-DATE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseGeneratedProguardFiles UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:exportReleaseConsumerProguardFiles UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibRuntimeToJarRelease UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseNativeLibs UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:stripReleaseDebugSymbols NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:copyReleaseJniLibsProjectOnly UP-TO-DATE
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:mergeReleaseGeneratedProguardFiles UP-TO-DATE
> Task :unityLibrary:exportReleaseConsumerProguardFiles UP-TO-DATE
> Task :unityLibrary:processReleaseJavaRes UP-TO-DATE
> Task :unityLibrary:bundleLibResRelease UP-TO-DATE
> Task :unityLibrary:bundleLibRuntimeToJarRelease UP-TO-DATE
> Task :unityLibrary:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:mergeReleaseNativeLibs UP-TO-DATE
> Task :unityLibrary:stripReleaseDebugSymbols UP-TO-DATE
> Task :unityLibrary:copyReleaseJniLibsProjectOnly UP-TO-DATE
> Task :launcher:processReleaseResources FAILED
52 actionable tasks: 2 executed, 50 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <2c344dfa67884d4ca623f814e4a08809>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <2c344dfa67884d4ca623f814e4a08809>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <2c344dfa67884d4ca623f814e4a08809>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <2c344dfa67884d4ca623f814e4a08809>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, Unity.Android.Gradle.AndroidGradle androidGradle, System.String workingdir, System.String task, System.Action`1[T] progress) (at <2c344dfa67884d4ca623f814e4a08809>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, Unity.Android.Gradle.AndroidGradle androidGradle, System.String workingdir, System.String task, System.Action`1[T] progress) (at <2c344dfa67884d4ca623f814e4a08809>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <2c344dfa67884d4ca623f814e4a08809>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <2c344dfa67884d4ca623f814e4a08809>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <2c344dfa67884d4ca623f814e4a08809>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <2c344dfa67884d4ca623f814e4a08809>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, AndroidPlayerBuildProgram.Data.AndroidPlayerBuildProgramOutput buildProgramOutput) (at <2c344dfa67884d4ca623f814e4a08809>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <2c344dfa67884d4ca623f814e4a08809>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.Int32 subtarget, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <0a81bd77f3334bdfa5d31008229edcac>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by coolishbee** [comment]
Can you share the code for all the gradle (base, main, launcher, settings) files you have set up?

**Comment by YoussefSayed34** [comment]
baseProjectTemplate.gradle:

```
allprojects {
    buildscript {
        repositories {**ARTIFACTORYREPOSITORY**
            google()
            mavenCentral()
            maven { url 'https://jitpack.io' } //added
            flatDir {
                dirs "${project(':unityLibrary').projectDir}/libs"
            }
        }

        dependencies {
            // If you are changing the Android Gradle Plugin version, make sure it is compatible with the Gradle version preinstalled with Unity
            // See which Gradle version is preinstalled with Unity here https://docs.unity3d.com/Manual/android-gradle-overview.html
            // See official Gradle and Android Gradle Plugin compatibility table here https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
            // To specify a custom Gradle version in Unity, go do "Preferences > External Tools", uncheck "Gradle Installed with Unity (recommended)" and specify a path to a custom Gradle version
            classpath'com.github.coolishbee:universal-sdk-android:3.0.9'
            classpath 'com.android.tools.build:gradle:4.0.1'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61"
            **BUILD_SCRIPT_DEPS**
        }
    }

    repositories {**ARTIFACTORYREPOSITORY**
        google()
        mavenCentral()
        maven {
            url 'https://jitpack.io' 
        }
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

gradleTemplate.properties:

```
org.gradle.jvmargs=-Xmx**JVM_HEAP_SIZE**M
org.gradle.parallel=true
unityStreamingAssets=**STREAMING_ASSETS**
# Android Resolver Properties Start
android.useAndroidX=true
android.enableJetifier=true
# Android Resolver Properties End
**ADDITIONAL_PROPERTIES**

android.enableR8=**MINIFY_WITH_R_EIGHT**
```

launcherTemplate.gradle (just replaced the ids):

```
apply plugin: 'com.android.application'

dependencies {
    implementation project(':unityLibrary')
    implementation 'androidx.multidex:multidex:2.0.1' //added
    }

android {
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        applicationId '**APPLICATIONID**'
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        multiDexEnabled true //added

        resValue "string", "facebook_app_id", "facebook_app_id"
        resValue "string", "facebook_client_token", "facebook_client_token"
        resValue "string", "google_web_client_id", "google_web_client_id"
        resValue "string", "apple_client_id", "com.your.service.id.here"
        resValue "string", "redirect_url", "https://redirect.url.here"
    }

    aaptOptions {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**SIGN**

    lintOptions {
        abortOnError false
    }

    buildTypes {
        debug {
            minifyEnabled **MINIFY_DEBUG**
            proguardFiles getDefaultProguardFile('proguard-android.txt')**SIGNCONFIG**
            jniDebuggable true
        }
        release {
            minifyEnabled **MINIFY_RELEASE**
            proguardFiles getDefaultProguardFile('proguard-android.txt')**SIGNCONFIG**
        }
    }**PACKAGING_OPTIONS****PLAY_ASSET_PACKS****SPLITS**
**BUILT_APK_LOCATION**
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
}**SPLITS_VERSION_CODE****LAUNCHER_SOURCE_BUILD_SETUP**

```

mainTemplate.gradle:

```
apply plugin: 'com.android.library'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.github.coolishbee:universal-sdk-android:3.0.9'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.61"
    **DEPS**
}

android {
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING_OPTIONS**
}**REPOSITORIES**
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' } // Added JitPack for universal-sdk
    }
}
```

**Comment by coolishbee** [comment]
`classpath'com.github.coolishbee:universal-sdk-android:3.0.9'` `android.enableR8=**MINIFY_WITH_R_EIGHT**`
Could you please delete just 2 lines and try again?

**Comment by YoussefSayed34** [comment]
The build was successful, yet another issue occurred which is whenever I press login button the app crashes.
Here are some useful logs:
[logcat-1_OnSceneSart(no-action-taken).txt](https://github.com/user-attachments/files/17587247/logcat-1_OnSceneSart.no-action-taken.txt)
[logcat-2_OnGoogleLoginButtonPress.txt](https://github.com/user-attachments/files/17587248/logcat-2_OnGoogleLoginButtonPress.txt)

**Comment by coolishbee** [comment]
If you're using Proguard, add the following to the proguard-user.txt file.

```
-kepp class com.universal.sdk.unitywrapper.** {*;}
-keep class io.github.coolishbee.** { *; }
```

**Comment by YoussefSayed34** [comment]
I already have these two lines to the proguard-user.txt

**Comment by coolishbee** [comment]
Can you share your project?

**Comment by YoussefSayed34** [comment]
Unfortunately, I can't do that, can you tell me what test cases you have in mind so I can give it a try.

**Comment by YoussefSayed34** [comment]
2 and 3 are actually ok, as I have disabled proguard and had the same issues, and universal-sdk-wrapper-release.aar exists in the right path.
So the issue is definitely the first point which is logical as we actually removed earlier the classpath'com.github.coolishbee:universal-sdk-android:3.0.9' line.
If I understand correctly this line gets the asset dependencies so removing it means missing dependencies am I right?

**Comment by YoussefSayed34** [comment]
2 and 3 are actually ok, as I have disabled proguard and had the same issues, and universal-sdk-wrapper-release.aar exists in the right path.
So the issue is definitely the first point which is logical as we actually removed earlier the classpath'com.github.coolishbee:universal-sdk-android:3.0.9' line.
If I understand correctly this line gets the asset dependencies so removing it means missing dependencies am I right?

**Comment by coolishbee** [comment]
The reasons why the class method cannot be found are as follows: 

1. When gradle does not receive the corresponding library. 

2. When the library's interface is obfuscated.
(You can actually check if the aar file is not obfuscated by extracting the build results.)

3. When assets/plugins/android/universal-sdk-wrapper-release.aar does not exist. 

Are all the problems ok?

**Comment by YoussefSayed34** [comment]
I tried resolving the dependencies using https://github.com/googlesamples/unity-jar-resolver

**Comment by coolishbee** [comment]
It is correct to remove the classpath line. Those are the libraries referenced during compilation and the universal sdk only requires implementation dependencies.

The current situation is that `com.universal.sdk.unitywrapper` of `universal-sdk-wrapper-release.aar` is called, but it seems that the `io.github.coolishbee` classes of the actual implementation part in `com.universal.sdk.unitywrapper` cannot be found.

If you use Resolver, please also check UniversalSDKDependencies.xml

**Comment by YoussefSayed34** [comment]
When I do that we go back to the gradle build issues, and it's logical as all that dependency resolver does is place the same `classpath'com.github.coolishbee:universal-sdk-android:3.0.9'` line in the mainTemplate.gradle.

**Comment by coolishbee** [comment]
If it still doesn't work, try updating to the major version of Unity 2022.3? I'm expecting a version update for gradle.

**Comment by YoussefSayed34** [comment]
I've updated the editor to the latest version of Unity 2021.3 (2021.3.45f1), The gradle issues seems to be gone but for some reason the build itself is not working properly.
So, I'm closing the issue as it no longer looks like an issue caused by the sdk rather a gradle bug that existed in the unity version I used, Thank you for your help!
