### ISSUE TITLE
Native view disappears and login process never exits when app resumes from background

### ISSUE THREAD

**Issue by marked-one** [coolishbee/universal-sdk-unity#7]
## What did you do?

- integrate SDK into an app
- run the app on a device
- start login process
- wait until native view appears
- move app to background
- resume

## What did you expect?

either native view doesn't disappear (preferred) or login process returns an error

## What happened actually?

native view disappears and login process never returns

## Your environment?

- Universal SDK v. 1.1.4
- Unity 2022.1.20f1
- Android 12
- haven't tested on iOS

## Screenshots or Log

not applicable

**Comment by coolishbee** [comment]
What kind of social login are you talking about? Exception handling is different for each social login API. It's not my control.

**Comment by marked-one** [comment]
Any native view (Google, Facebook, Apple) behaves the same way here.

**Comment by marked-one** [comment]
Some update: in case of Google, if I try to login with Google again (after the native dialog disappears), error 12502 is returned  instead of the login dialog being opened. And if I try one more time - it successfully opens the dialog again.

**Comment by marked-one** [comment]
To me this issue is related to Android killing activities that aren't displayed.

**Comment by marked-one** [comment]
The best choice here would be to restore previously opened activities in native code. Which will include reopening any third-party dialogs, as if they were never closed. From what I understand this is normal Android behaviour.
