### ISSUE TITLE
Path to settings is hardcoded

### ISSUE THREAD

**Issue by marked-one** [coolishbee/universal-sdk-unity#8]
I had to move the SDK to a folder (for me it was just a folder containing all non-native plugins, but you can also imagine someone who tries to move this sdk to a package). 

Note: for me personally this issue was minor, there are many ways to overcome it. Just decided to report it anyway.

## What did you do?

Moved UniversalSDK to a folder (e.g. Assets/Folder/UniversalSDK

## What did you expect?

Successful creation of Settings asset from main menu. 

## What happened actually?

I was unable to create the Settings asset from main menu. 

## Your environment?

Universal SDK v. 1.1.4
not applicable

## Screenshots or Log

not applicable

**Comment by coolishbee** [comment]
I'm sorry, I know about the issue and I'm thinking about improving it.
